INSERT INTO TEAM (ID, TEAM_NAME) VALUES (1, 'testTeam');

INSERT INTO MEMBER_TEST (ID, USERNAME, TEAM_ID) VALUES (1, 'testMember', 1);
INSERT INTO MEMBER_TEST (ID, USERNAME, TEAM_ID) VALUES (2, 'testMember2', 1);