INSERT INTO TEAM (ID, TEAM_NAME) VALUES (1, 'testTeam');
INSERT INTO TEAM (ID, TEAM_NAME) VALUES (2, 'testTeam2');
INSERT INTO TEAM (ID, TEAM_NAME) VALUES (3, 'testTeam3');

INSERT INTO MEMBER_TEST (ID, USERNAME, TEAM_ID) VALUES (1, 'testMember', 1);
INSERT INTO MEMBER_TEST (ID, USERNAME, TEAM_ID) VALUES (2, 'testMember2', 2);

INSERT INTO MEMBER_TEST2 (ID, USERNAME) VALUES (1, 'testMember');
INSERT INTO MEMBER_TEST2 (ID, USERNAME) VALUES (2, 'testMember2');

INSERT INTO LOCKER (ID, MEMBER_TEST2_ID) VALUES (1, 1);
INSERT INTO LOCKER (ID, MEMBER_TEST2_ID) VALUES (2, 2);